set encoding=utf-8

" for macOS only
set backspace=2

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set nu
"set mouse+=a

set hlsearch


syntax enable
set laststatus=2
set t_Co=256
let g:solarized_termcolors=256
set background=dark
colorscheme solarized
"color desert
"powerline
source /usr/local/lib/python3.9/site-packages/powerline/bindings/vim/plugin/powerline.vim

set cursorline
set cursorcolumn

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

"vaundle"
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
call vundle#end()

filetype plugin indent on

"YCM"
"Bundle 'Valloric/YouCompleteMe'

"TabNine
Plugin 'codota/tabnine-vim'

"NerdTree
map <f2> :NERDTreeToggle<cr>
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
let g:NERDTreeWinPos='left'
let g:NERDTreeSize=30
let g:NERDTreeShowLineNumbers=1
let g:NERDTreeHidden=0
